#! /bin/csh -f
##################################################
#
# Usage:
#     get_mustang_noise-spectrogrm_plots
#
###################################################

#if ($#argv != 1) then
#	echo "Usage:"
#	echo "    get_mustang_noise-spectrogrm_plots"
#	echo ""
#	exit 1
#endif 

umask 002 
#######################################
# GET IDA/II (non-experimental) STATION LIST
# UGH --- I HATE THIS. I WANT MY DB...
set stalist = (AAK ABPO ALE ARTI ASCN BORG BRVK CMLA COCO DGAR EFI ERM ESK FFC HOPE JTS KAPI KDAK KIV KURK KWJN LVZ MBAR MSEY MSVF NIL NNA OBN PALK PFO RAYN RPN SACV SHEL SIMI SUR TAU TLY UOSS WRAB)
#
# NOTE: Above list missing BFO and Xxxx stations with non-standard components (aka 'NE') or locations. E.g. XBFO and XPFO
#######################################

#######################################
# Loop through stations retrieving plots from MUSTANG and saving them for Web viewing
foreach sta ($stalist)

    /ida/dcc/bin/mustango noise-spectrogram ii $sta 00,10 lhz,lh1,lh2,bhz,bh1,bh2 \
        --plot.powerscale.height=20 --plot.powerscale.width=200 --outdir /ida/dcc/qc/PLOTS/PLOTS.mustang
end
######################################

######################################
# Now handle some non-standard cases/stations

# BFO 'NE' horizontals
    /ida/dcc/bin/mustango noise-spectrogram ii bfo 00,10 lhz,lhn,lhe,bhz,bhn,bhe \
        --plot.powerscale.height=20 --plot.powerscale.width=200 --outdir /ida/dcc/qc/PLOTS/PLOTS.mustang
# XBFO experimental sensors
    /ida/dcc/bin/mustango noise-spectrogram ii XBFO 50,55,60 lhz,lhn,lhe,bhz,bhn,bhe \
        --plot.powerscale.height=20 --plot.powerscale.width=200 --outdir /ida/dcc/qc/PLOTS/PLOTS.mustang

# XPFO sensors
    /ida/dcc/bin/mustango noise-spectrogram ii XPFO 00,10,20,30,40,50,60,70 lhz,lh1,lh2,bhz,bh1,bh2 \
        --plot.powerscale.height=20 --plot.powerscale.width=200 --outdir /ida/dcc/qc/PLOTS/PLOTS.mustang
exit
