#!/usr/bin/env python3
import tkinter as tk


class Application(tk.Frame):
    """Main Tkinter Application Class"""

    def __init__(self, master=None):
        tk.Frame.__init__(self, master)
        self.grid()
        self.create_widgets()

    def create_widgets(self):
        self.quit_button = tk.Button(self, text='Quit', command=self.quit())
        self.quit_button.configure(width='60')
        self.quit_button.grid()

my_app = Application()
my_app.master.title('Sample application')
my_app.mainloop()
