#!/usr/bin/env python3
#######################################################################################################################
# Copyright (C) 2016  Regents of the University of California
#
# This is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License (GNU GPL) as published by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# A copy of the GNU General Public License can be found in LICENSE.TXT in the root of the source code repository.
# Additionally, it can be found at http://www.gnu.org/licenses/.
#
# NOTES: Per GNU GPLv3 terms:
#   * This notice must be kept in this source file
#   * Changes to the source must be clearly noted with date & time of change
#
# If you use this software in a product, an explicit acknowledgment in the product documentation of the contribution
# by Project IDA, Institute of Geophysics and Planetary Physics, UCSD would be appreciated but is not required.
#######################################################################################################################
import os
from os.path import join
import argparse
import sys
import logging
import datetime

from fabulous.color import red, green, bold


version = '0.1.0'
parser = argparse.ArgumentParser(description="Analyze Compact Trillium shake table data.")
parser.add_argument('config', action="store", default='config',
                    help="Configuration file (located in $IDA_CAL_RAW_DIR/shaketable)")
parser.add_argument('-v', '--version', action='version', version=version)
parser.add_argument('-d', '--debug', action='store_true', help='Enabled debug mode for verbose output.')

args = parser.parse_args()
debug = args.debug
config_name = args.config

if not '.yaml' in args.config:
   config_name = args.config + '.yaml'

if not os.environ.get('IDA_CAL_RAW_DIR'):
    print(red(bold('The env var IDA_CAL_RAW_DIR must be set to the root directory ' + \
                   'of the raw calibration data.')))
    sys.exit(1)

# set up logging
class ConsoleLogFilter(logging.Filter):

   def filter(self, record):
      if record.levelno == logging.WARN:
         record.msg = red(record.msg)
      elif record.levelno == logging.DEBUG:
         record.msg = green(bold(record.msg))
      elif record.levelno >= logging.ERROR:
         record.msg = red(bold(record.msg))
      return True


logfile = os.path.abspath(__file__ + '.log')
# set up logging to file - see previous section for more details
logging.basicConfig(level=logging.DEBUG, 
                    format='%(asctime)s %(name)s %(levelname)s %(message)s',
                    datefmt='%m-%d %H:%M:%S',
                    filename=logfile,
                    filemode='w')

chndlr = logging.StreamHandler()
if debug:
    chndlr.setLevel(logging.DEBUG)
else:
    chndlr.setLevel(logging.WARN)
confmtr = logging.Formatter('%(levelname)s: %(message)s')
chndlr.setFormatter(confmtr)
chndlr.addFilter(ConsoleLogFilter())

logging.getLogger('').addHandler(chndlr)
logger = logging.getLogger('SHAKETABLE')

#   logger.setLevel(logging.DEBUG)  # allow control via handler(s)
#   fhndlr = logging.FileHandler(logfile)
#   fhndlr.setLevel(logging.DEBUG)
#   filefmtr = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s: %(message)s')
#   fhndlr.setFormatter(filefmtr)
#   logger.addHandler(fhndlr)
#   logger.addHandler(chndlr)

logger.info('='*72)
logger.info('Starting Shaketable analysis: ' + \
            datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'))

from ida.calibration.shaketable import ShakeConfig

subdir = 'shaketable'
cfg_dir = join(os.environ['IDA_CAL_RAW_DIR'], subdir)
cfg_fn = join(cfg_dir, config_name)

config = ShakeConfig(cfg_fn, shaketable_subdir=subdir, debug=debug, logger=logger)

if config.ok:
     if not config.read_msfile():
        logger.critical('Error reading miniseed file: ' + config.ms_filename)
        sys.exit(1)

     if not config.prepare_traces():
        logger.critical('Could not prepare traces. Quitting.')
        sys.exit(1)

     plot_fns, ms_fns, resfn = config.analyze()

     done = input('Hit enter to exit...')

else:
   logger.critical('Quitting due to problems with configuration or environment.')

logger.info('Exiting: ' + datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
logger.info('='*72)

