#! /bin/csh -f
##################################################
#
# Usage:
#     get_dqa_plots
#
##################################################
set path = (/usr/local/bin $path)
umask 002
#######################################
# GET IDA/II (non-experimental) STATION LIST
# UGH --- I HATE THIS. I WANT MY DB...
set stalist = (AAK ABPO ALE ARTI ASCN BORG BORK BRVK CMLA COCO DGAR EFI ERM ESK FFC HOPE JTS JZAX KAPI KDAK KIV KURK KWJN LVZ MBAR MSEY MSVF NIL NNA OBN PALK PFO RAYN RPN SACV SHEL SIMI SUR TAU TLY UOSS WRAB)
#
# get start and end dates for last 365 days
set year = `date +%Y`
@ lastyear = ($year - 1)
set monthday = `date +%m-%d`
set sdate = "${lastyear}-${monthday}"
set edate = "${year}-${monthday}"

#######################################
# Loop through stations retrieving plots from MUSTANG and saving them for Web viewing
foreach sta ($stalist)

  /ida/dcc/scripts/dqa-plots.py CoherencePBM:4-8               plot ii $sta lhz-lhz   00-10 $sdate $edate --save --name last365 --outdir /ida/dcc/qc/PLOTS/metrics/ -q
  /ida/dcc/scripts/dqa-plots.py CoherencePBM:4-8               plot ii $sta lhnd-lhnd 00-10 $sdate $edate --save --name last365 --outdir /ida/dcc/qc/PLOTS/metrics/ -q
  /ida/dcc/scripts/dqa-plots.py CoherencePBM:4-8               plot ii $sta lhed-lhed 00-10 $sdate $edate --save --name last365 --outdir /ida/dcc/qc/PLOTS/metrics/ -q

  /ida/dcc/scripts/dqa-plots.py CoherencePBM:90-110            plot ii $sta lhz-lhz   00-10 $sdate $edate --save --name last365 --outdir /ida/dcc/qc/PLOTS/metrics/ -q
  /ida/dcc/scripts/dqa-plots.py CoherencePBM:90-110            plot ii $sta lhnd-lhnd 00-10 $sdate $edate --save --name last365 --outdir /ida/dcc/qc/PLOTS/metrics/ -q
  /ida/dcc/scripts/dqa-plots.py CoherencePBM:90-110            plot ii $sta lhed-lhed 00-10 $sdate $edate --save --name last365 --outdir /ida/dcc/qc/PLOTS/metrics/ -q

  /ida/dcc/scripts/dqa-plots.py CoherencePBM:200-500           plot ii $sta lhz-lhz   00-10 $sdate $edate --save --name last365 --outdir /ida/dcc/qc/PLOTS/metrics/ -q
  /ida/dcc/scripts/dqa-plots.py CoherencePBM:200-500           plot ii $sta lhnd-lhnd 00-10 $sdate $edate --save --name last365 --outdir /ida/dcc/qc/PLOTS/metrics/ -q
  /ida/dcc/scripts/dqa-plots.py CoherencePBM:200-500           plot ii $sta lhed-lhed 00-10 $sdate $edate --save --name last365 --outdir /ida/dcc/qc/PLOTS/metrics/ -q

  /ida/dcc/scripts/dqa-plots.py StationDeviationMetric:90-110  plot ii $sta lhz          00 $sdate $edate --save --name last365 --outdir /ida/dcc/qc/PLOTS/metrics/ -q
  /ida/dcc/scripts/dqa-plots.py StationDeviationMetric:90-110  plot ii $sta lh1          00 $sdate $edate --save --name last365 --outdir /ida/dcc/qc/PLOTS/metrics/ -q
  /ida/dcc/scripts/dqa-plots.py StationDeviationMetric:90-110  plot ii $sta lh2          00 $sdate $edate --save --name last365 --outdir /ida/dcc/qc/PLOTS/metrics/ -q
  /ida/dcc/scripts/dqa-plots.py StationDeviationMetric:90-110  plot ii $sta lhz          10 $sdate $edate --save --name last365 --outdir /ida/dcc/qc/PLOTS/metrics/ -q
  /ida/dcc/scripts/dqa-plots.py StationDeviationMetric:90-110  plot ii $sta lh1          10 $sdate $edate --save --name last365 --outdir /ida/dcc/qc/PLOTS/metrics/ -q
  /ida/dcc/scripts/dqa-plots.py StationDeviationMetric:90-110  plot ii $sta lh2          10 $sdate $edate --save --name last365 --outdir /ida/dcc/qc/PLOTS/metrics/ -q

  # lets let server take a breath...
  sleep 1

end
######################################

exit
