#! /bin/csh -f
#
# $Id: vh_gen,v 1.2 2015/11/25 17:08:37 dauerbach Exp $
#
##################################################
#
# One(?) off script to process LH data into VH for all days since 
# start of IDA Linux era, when old VH gen process became obsolete.
#
# Uses vhfilt to generate VH data from existing miniseed files in
# /ida/tmp/daily/miniseed/2015jjj/DONE for day 2015110 thru end of 2015
# Starts processing with day 109 so that the trimming after the filtering
# doesn't cut of any data from day 110.
#
# Saves VH data in station specific files: <sta>.vh.ms in dir
# /ida/tmp/daily/miniseed
#
# Usage:
#     vh_gen
#
###################################################

#if ($#argv != 1) then
#	echo "Usage:"
#	echo ""
#→  echo "    vf_gen YYYYDDD"
#→  echo "ex: vf_gen 2015150"
#→  echo ""
#→  echo "You may use filename wildcards:"
#→  echo "    vf_gen 20151??"
#	exit 1
#endif 

# UGH --- I HATE THIS. I WANT MY DB...
set stalist = (AAK ABPO ALE ARU ASCN BFO BORG BRVK CMLA COCO DGAR EFI ERM ESK FFC HOPE JTS JZAX KAPI KDAK KIV KURK KWAJ LVZ MBAR MSEY MSVF NIL NNA OBN PALK PFO RAYN RPN SACV SHEL SUR TAU TLY UOSS WRAB)


set MINISEEDDIR = /ida/tmp/daily/miniseed

if (! -d $MINISEEDDIR) then
	echo "Error: Directory $MINISEEDDIR not found."
	exit 1
endif

cd $MINISEEDDIR

foreach sta ($stalist)

	echo "Processing: $sta"

	# concat allexisting ms files (in fact this will only include from 2015-109 forward)
	cat 2015???/DONE/$sta*.ms > $sta.vh_src.ms

	# have dataselect cleanup the epochs 
	dataselect -ts 2015:109 -te 2015:321:12:00 $sta.vh_src.ms -o $sta.vh_src_clean.ms
 
	# run vhfilt
	vhfilt < $sta.vh_src_clean.ms > $sta.vh_raw.ms

	# crop start/end
	dataselect -ts 2015:110 -te 2015:321 $sta.vh_raw.ms -o $sta.vh.ms
 
end

exit


###################################################
# $Log: vh_gen,v $
# Revision 1.2  2015/11/25 17:08:37  dauerbach
# Add AAK back to list of stations and fix usage notes
#
# Revision 1.1  2015/11/19 23:25:31  dauerbach
# initial load of vh_gen (w/o AAK) and vh_send
#
#
###################################################
